/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'channelId' : IDL.Nat,
  'authorId' : IDL.Principal,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const StudentProfile = IDL.Record({
  'displayName' : IDL.Text,
  'instagramHandle' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const Channel = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAllMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'initializeChannels' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'postMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'channelId' : IDL.Nat,
    'authorId' : IDL.Principal,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const StudentProfile = IDL.Record({
    'displayName' : IDL.Text,
    'instagramHandle' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const Channel = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAllMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'initializeChannels' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'postMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };