/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Message {
  'content' : string,
  'channelId' : bigint,
  'authorId' : Principal,
  'authorName' : string,
  'timestamp' : bigint,
}
export interface StudentProfile {
  'displayName' : string,
  'instagramHandle' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, [] | [string], [] | [string]],
    undefined
  >,
  'getAllMessages' : ActorMethod<[bigint], Array<Message>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelMessages' : ActorMethod<[bigint, bigint], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'initializeChannels' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChannels' : ActorMethod<[], Array<Channel>>,
  'postMessage' : ActorMethod<[bigint, string], Message>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];